### ISSUE TITLE
Module should not venture outside `directory`

### ISSUE THREAD

**Issue by silverwind** [SamVerschueren/tsd#30]
Given a directory structure like

```
parent
  node_modules
  child
    package.json
    node_modules
```

When running with `directory` set to `child`, `tsd` tries to check files in `parent/node_modules` which it absolutely should not. `parent/node_modules` is a symlink in my case.

**Comment by SamVerschueren** [comment]
Just to be sure. How do you set the `directory` to `child`? Do you run `tsd parent/child` or do you have a `package.json` somewhere pointing to `child`?

Because the `directory` option is meant to point to a directory with only test files. Something like this

```
parent
  node_modules
  child
    package.json
    node_modules
    test-dir
      test.test-d.ts
      test2.test-d.ts
```

And then set `directory` to `test-dir` inside `parent/child/package.json` and run `tsd parent/child`.

Do I miss something here? Would be nice if I could reproduce this in a test case or something.

**Comment by BendingBender** [comment]
@silverwind Would you mind testing my branch (https://github.com/BendingBender/tsd/tree/ignore-errors-from-node-modules) and reporting whether it fixes the problem for you? Thanks!
