### ISSUE TITLE
use local typescript if installed.

### ISSUE THREAD

**Issue by magicdawn** [SamVerschueren/tsd#85]
typescript@4 support variadic tuple type & labeled tuple  about 2 month ago.
The vscode can understand the code, but tsd can not.

![image](https://user-images.githubusercontent.com/4067115/97800760-ce6c8500-1c72-11eb-9ada-553ef67566c8.png)

**Comment by voxpelli** [comment]
Agree, maybe one can use something like ['import-local`](https://github.com/sindresorhus/import-local)  to achieve that

**Comment by papb** [comment]
I don't think it's that easy, unfortunately, I think `tsd` ships with its own patched typescript implementation.

**Comment by voxpelli** [comment]
Yes, seems like it hence #62, would be good if that patching could eventually be removed and upstreamed to core, but probably easier said than done

**Comment by papb** [comment]
@voxpelli By the way, I have been using [expect-type](https://www.npmjs.com/package/expect-type) instead of tsd for a while now, has worked perfectly for me, maybe it works for your use case too.

**Comment by SamVerschueren** [comment]
Just released a new version with TypeScript@4.1 support.

I'm working on an automated solution which creates a patched TypeScript release whenever TypeScript itself creates a new release. Together with [allow testing multiple TypeScript versions](https://github.com/SamVerschueren/tsd/issues/47#issuecomment-663980068), it should automatically be picked up on the next test run.

I'm going to close this for now because as you said, I need a patched TS which doesn't work if I use the locally installed TypeScript version.
